import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useApi } from '../api/client'
import CanvasPlayer from '../components/CanvasPlayer'

export default function PlayerPage() {
  const { clipId } = useParams()
  const navigate = useNavigate()
  const api = useApi()

  const [clip, setClip] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    async function loadClip() {
      try {
        const data = await api.get(`/clips/${clipId}`)
        setClip(data)
      } catch (err) {
        setError('Failed to load clip')
      } finally {
        setLoading(false)
      }
    }
    loadClip()
  }, [clipId])

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center">
        <p className="text-gray-400 text-sm">Loading...</p>
      </div>
    )
  }

  if (error || !clip) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center">
        <p className="text-red-400 text-sm">{error || 'Clip not found'}</p>
      </div>
    )
  }

  const isProcessed = clip.job?.status === 'complete'

  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <nav className="flex items-center gap-4 px-6 py-4 border-b border-gray-800">
        <button
          onClick={() => navigate(-1)}
          className="text-gray-400 hover:text-white transition-colors text-sm"
        >
          ← Back
        </button>
        <span className="font-medium text-sm text-gray-300 truncate">
          {clip.filename}
        </span>
      </nav>

      <main className="max-w-5xl mx-auto px-6 py-8">
        <CanvasPlayer
          videoUrl={clip.video_url}
          resultUrl={clip.result_url}
        />

        {/* Coaching feedback — generated by Celery task, available once processed */}
        {isProcessed && clip.feedback && (
          <div className="mt-8">
            <h2 className="text-lg font-semibold mb-4">Coaching feedback</h2>
            <div className="bg-gray-900 border border-gray-800 rounded-xl p-5 text-sm text-gray-300 leading-relaxed">
              {renderFeedback(clip.feedback)}
            </div>
          </div>
        )}
      </main>
    </div>
  )
}


function renderFeedback(text) {
  return text.split('\n').map((line, i) => {
    if (!line.trim()) return <div key={i} className="h-2" />

    const isBold = line.startsWith('**') && line.includes('**', 2)
    if (isBold) {
      const inner = line.replace(/^\*\*/, '').replace(/\*\*$/, '')
      return <p key={i} className="font-semibold text-white mt-3 first:mt-0">{inner}</p>
    }

    const parts = line.split(/\*\*(.*?)\*\*/g)
    return (
      <p key={i} className="text-gray-300">
        {parts.map((part, j) =>
          j % 2 === 1 ? <strong key={j} className="text-white">{part}</strong> : part
        )}
      </p>
    )
  })
}
